export const AUTH_BOOTING = 'HMS/AUTH/BOOTING';
export const AUTH_AUTHENTICATED = 'HMS/AUTH/AUTHENTICATED';
export const AUTH_ANONYMOUS = 'HMS/AUTH/ANONYMOUS';
export const AUTH_LOGGED_OUT = 'HMS/AUTH/LOGGED_OUT';
